<body id=b><script id=x>/*
<body onload=setInterval("c.width|=Q=Math.cos;for(i=57;i--;)c.getContext('2d').fillRect(99+i*Q(o),i*3,z=2+Q(o+=14),z)",o=9)><canvas id=c>
<body onload=with(c.getContext('2d'))for(m=8e4;m;rotate(--m&-m&m/2?11:-11))fillRect(0,0,1,1),translate(1,0)><canvas id=c>
<p onmousemove=b.innerHTML+='\u200B\u2571\u2572'[event.screenX%3] id=b>Hi
<body onload=setInterval(F=";t+=.1;Q=Math.cos;for(x=n=c.height=300;x-=4;)for(y=n;y-=4;d.fillRect(x,y,E,Z^z?4:E))for(D=0;(E=4-D/2)&&F<F[(t+D*Q(T=x/n-.5+Q(t/9))&7)*8|(Z=3.7+D*Q(T-8)&7)*4|(6.5-D*y/n-E)];z=Z)D+=1/8",t=55),d=c.getContext('2d')><canvas id=c>
<body onload=E=c.getContext("2d"),setInterval(F="t+=.2,Q=Math.cos;c.height=300;for(x=h;x--;)for(y=h;y--;E.fillRect(x*4,y*4,b-d?4:D/2,D/2))for(D=0;'.'<F[D*y/h-D/2|0?1:(d=t+D*Q(T=x/h-.5+Q(t)/8)&7)|(3.5+D*Q(T-8))<<3]&&D<8;b=d)D+=.1",t=h=75)><canvas id=c>
<body onload=setInterval("for(t-=.1,x=h,c.height=300,Q=Math.cos;x--;)for(y=h;y--;c.getContext('2d').fillRect(x*4,y*4,N,N))for(N=D=4;X=D*x/h-D/2,Y=D*y/h-D/2,Z=D/2-9,D+=d=(X*X+Y*Y*Q(t/6+Q(D-X-Y))+Z*Z)/9-1+Q(X+t)*Q(Y-t),.1<d*N;)N-=.1",t=h=75)><canvas id=c>
<body onload="for(r=q='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEA5h0AAOYdAAABAAgA',f=t=0;t++<6e5;q+=f&9)f+='G    G                    UZZUUZUZ5    5                    5    5                    P    P            PL        G            GC5    5(/(@5                                '.charCodeAt(t/1441%64)/500;new Audio(r+btoa(q)).play()">JS is jarig \o/
<body onload=setInterval(F="for(X=x=h=c.height|=Q=Math.cos;x--;)for(i=j=1;i<h;c.getContext('2d').fillRect(x*2,i,U^X?1.7:2,j-i/h,i+=j))j^1||((U=X,X=15*Q(t)-i/8*Q(T=t+x/h-.5)+4)|(Y=15*Q(t+8)-i/8*Q(T+8)+4))<8&&F[X|Y<<3]<Q&&(j=19-i/8);t+=88",t=9)><canvas id=c>
<canvas id=c><script>t=0;S=String.fromCharCode;c.outerHTML='<canvas width=768 height=432 id=d style=position:fixed;left:0;top:0;width:100%;height:100%;background:#210>';for(x in g=d.getContext('experimental-webgl'))g[x[0]+x[6]]=g[x];with(g){for(p=cP();s=cS(t+35632);ce(s),aS(p,s))sS(s,t++?'attribute vec4 t;void main(){gl_Position=t;}':'precision lowp float;uniform float t;float a(vec4 r,int d){float f=0.,s=32.;for(int i=0;i<48;i++)if(i<d){vec4 n=fract(r/32.)-.5;f+=(n.x*n.x+n.z*n.z)*s;s*=.5;r.xz*=mat2(1.2,1.4,-1.4,1.2);}return f;}float f(inout vec4 r,vec4 y,int d){float f=0.,s=32.;for(int i=0;i<48;i++)if(.1<s&&f<32.){f+=s=(r.y-a(r,d))*.3;r+=s*y;}return f;}void main(){vec4 r=vec4(1.2+cos(t/8.)*8.,24.+cos(t*.3),t,0.),y=normalize(vec4(gl_FragCoord.xy/vec2(24.,13.5)-16.+cos(t),8.,0.)),m=vec4(.1,0.,min(1.,f(r,y,8)/32.),0.);gl_FragColor=mix(vec4(f(r,normalize(vec4(a(r+m.xyyy,8),a(r+m.yxyy,8),a(r+m.yyxy,8),a(r,8))-a(r,8)),2)/32.),vec4(.8,1.2,1.4,1.)*y.z,m.z)-pow(t/32.-1.,32.);}');vA(eV(bf(34962,cB())),2,5126,lo(p),ug(p),bD(34962,new Float32Array([1,1,1,-3,-3,1]),34962+82));for(r=q='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEA5h0AAOYdAAABAAgA';t<5e5;t++)q+=S(Math.random()+t/(32.+Math.cos(t/8.))%5);o=new Audio(r+btoa(q));m=function(){dr(4,uniform1f(gf(p,'t'),o.currentTime),3);requestAnimationFrame(m)};m(o.play())}<>
<body id=b><script>b.innerHTML='<canvas id=d style=width:99%>';for(x in g=d.getContext('experimental-webgl'))g[x[t=0]+x[6]]=g[x];with(g){for(p=cP(q=' t;void main(){');s=cS(t+35632);ce(s),aS(p,s))sS(s,t++?'attribute vec4'+q+'gl_Position=t;}':'uniform '+(w='lowp float')+q+w+' C,u,r=sin(t),s,e=1.5,d;lowp vec3 P=gl_FragCoord.xyz/75.+mod(length(gl_FragCoord)*t,.03)-2.,p=vec3(r,cos(t),e+r),F=normalize(vec3(p.z*P.x,(P.y+e)*length(p),-p.x*P.x)-p*e),v;for(int i=0;i<99;++i)if(e>C*.001&&C<4.){v=p;d=1.;for(int n=0;n<6;++n){r=length(v);if(r<4.)d=pow(r,5.)*6.*d+1.,e=sin(s=6.*acos(v.z/r)),v=vec3(e*cos(u=6.*atan(v.y,v.x)),e*sin(u),cos(s))*pow(r,6.)+p;}C+=e=.5*log(r)*r/d;p+=F*e;gl_FragColor+=vec4(vec3(p-F+2.)*.01,d);}}');for(r='data:audio/wav;base64,UklGRl9vT19XQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgA';t<153;t+=.001)q+='1014501320214020'[t%16^(t/4&4)]*t*42&9;o=new Audio(r+btoa(r+q));vA(eV(bf(k=34962,cB())),2,5126,lo(p),ug(p),bD(k,new Float32Array([1,1,1,-3,-3,1]),o.loop=k+82));o.play(setInterval('g.dr(4,g.uniform1f(g.gf(p,"t"),t+=.01),3)',33))}<>
p<canvas id=d width=999 height=470><script>for(k in g=d.getContext('experimental-webgl'))g[k.match(/^..|[A-Z]|1f$/g).join(t='')]=g[k];with(g){for(p=crP(q=' p;void main(){');s=crS(t+35632);coS(s),atS(p,s))shS(s,t++?'attribute vec4'+q+'gl_Position=p;}':'uniform lowp float'+q+'lowp vec4 l=3.-gl_FragCoord/99.;gl_FragColor=cos(l*tan(l-p)+l/l.y*l.x);}');setInterval('g.drA(4,g.un1f(g.geUL(p,"p"),t+=44),3)',veAP(enVAA(biB(k=34962,crB())),2,5126,liP(p),usP(p),buD(k,new Float32Array([1,1,1,-3,-3,1]),k+82)))}<>
<body id=b><script>H='47-`-`-6:F6Z<P+6*<*<(-D,F2,,,c,<,c+20<*20<>Bx?P(Fcc,2,<<c';b.innerHTML='<h1>JS1K Speech Synthesizer<input id=d value="diz is a spich syntheSizer in oan kay. type your text and press enter" style=display:block;background:pink;width:99%;height:9em><audio id=a autoplay controls>';(onkeypress=function(e){M=e&&e.which^13?String.fromCharCode(e.which):document.getElementById('d').value;for(h=g=l=k=s=0,S='';s<M.length;s+=1/1024,S+=String.fromCharCode(Math.min(255,t<0?0:0|t)))if(t=128,f=g,g=h,j=k,k=l,~(p='oijuaeEwvTzZbdmnrlgfhsSptk'.indexOf(M[0|s])))b=g,c=f,d=1-H.charCodeAt(p*5+2|a)/255,l=d*(b*2*Math.sin(H.charCodeAt(p*5+0|a)/25)-d*c)+(p>20?Math.random():s*16%1)-.5,a^=1,h=l,b=k,c=j,d=1-H.charCodeAt(p*5+2|a)/255,l=d*(b*2*Math.sin(H.charCodeAt(p*5+0|a)/25)-d*c)+(p>20?Math.random():s*16%1)-.5,a^=1,t+=Math.min(1,4*Math.sin(Math.PI*s))*((h+l)*H.charCodeAt(p*5+4)+(g+k)/2+(f+j)/8);document.getElementById('a').src='data:audio/wav;base64,UklGRl9vT19XQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgA'+btoa('data:audio/wav;base64,UklGRl9vT19XQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgA'+S)})()<>
<pre id=p><script>n=setInterval("for(n+=7,i=k,P='p.\\n';i-=1/k;P+=P[i%2?(i%2*j-j+n/k^j)&1:2])j=k/i;p.innerHTML=P",k=64)<>
<canvas id=c style=top:0;left:0;width:100%;height:100%;position:fixed><script>for(k in g=c.getContext('experimental-webgl'))g[k.match(/^..|[A-Z]|1f$/g).join('')]=g[k];with(g){for(p=crP(t=2);t;coS(s),atS(p,s))shS(s=crS(35634-t),--t?'uniform lowp float t;void main(){lowp vec4 P=vec4(0,0,-2,0),D=gl_FragCoord/vec4(150,75,1,1)-1.,S=vec4(cos(t),sin(t),cos(t*.9),0)*.8,C=vec4(.4,.6,.7,9),f,T;for(int r=0;r<99;r++){T=P;T.w=dot(S,S)/4.;lowp float s=D.z=1.,k=dot(T,T);for(int m=0;m<7;m++)k<4.?s*=4.*k,f=2.*T.x*T,f.x=2.*T.x*T.x-k,k=dot(T=f+S,T):k;s=sqrt(k/s)*log(k)/4.;P+=D/length(D)*s;if(.001>s){C*=log(k);break;}}gl_FragColor=C+D.y*.4;}':'attribute vec4 p;void main(){gl_Position=p;}');setInterval('g.drA(4,g.un1f(g.geUL(p,"t"),t+=.01),3)',veAP(enVAA(biB(k=34962,crB())),2,5126,liP(p),usP(p),buD(k,new Float32Array([1,1,1,-3,-3,1]),k+82)))}<>
<canvas id="c"><script>E="A=document.body.children.c;B=A.getContext('2d'~=1$&31$&992(E&19)?1;	n=@nB#[A#)onkeyup=0};D=[setInterval(@=innerWidth-30;A.heigh@/2;	n=@n=[t,n,S,8+$*S&8)|(X+y+t*s+t*c8&7]){w=X=x=;v=y=;z=2]z+n/@ a=s=yG=F,r=u;a=c=X	;$~)F<G?(F,F1/uS=c/u):(G,G1/rS=32*s/r)}	n=@i<15;i++){2];j=38;i?1X=(+,;Y=(,+;ji?random(8-42]=(b-t/16+9.42%6.28)-3.14;z-atan2(Y-=v,X-=w~i&&>.5?=[sqrt(X*X+Y*Y),@/2-@*b,i,0,++n]	D.sort(+x[-y[}~n)	a=[,a/@ F=@/2//[,c=8,u=v=+1=[3]=c=1,@,0%)'):a!ca)	'+v+'%)'atob('CBF+/p6f9AC9bsP/w/dqvdvb2NvD29sb'),y=8,@/4,b!yb)d>>y&1,v),9)]";"@A.widthMath.cos(b)B[i][function(x,y){B.fillStyle='hsl('+D[n][2]+'1,99%,%=1;u=a<0?-a:a,F=(a<0?d:1-d)/u;onkeydownMath.sin(b).charCodeAt(x++%73)	for(?B.fillRect(a,b,u:A[j]-A[j+2];D[n]A[x.which]=--;*t/8;x|=y<<5;,i=0;Math.+=0]1.1,return)*b=,d=:0}F/41]t= -.5,!-=F;#[n]=$(x~);,x".replace(/.([%-}]+)/g,function(x,y){E=E.split(x[0]).join(y)});eval(E)<>
<body onload=N=[K=R.getContext('2d')];for(t=B=127,I=K.getImageData(0,0,q=64,q);t--;$=Math.cos)N[t]=t/43&1;setInterval("t++;for(i=y=-1;y<1;y+=A)for(x=-1;x<1;x+=A=1/32,I.data[i+=4]=h+h)for(m=C=$(a=t/86),S=$(a+8),c=$(b=t/B),s=$(b+8),u=x*C+S,v=y*c-u*s,u=u*c+y*s,w=C-x*S,X=q+9*$(a+b),Y=q+9*$(b-a),Z=t,h=B;--h&&m<q;X+=u,Y+=v,Z+=w)for(m=1;N[X*m&B]+N[Y*m&B]+N[Z*m&B]<2&&m<q;m*=3);K.putImageData(I,0,0)",9)><canvas id=R style=width:100%>
<body onload=setInterval("S=Math.sin;with(R.getContext('2d'))for(fillRect(0,0,300,150,drawImage(R,9,2,282,148,0,3,300,150),fillStyle='rgba(99,0,42,.01)'),a+=x=88;x--;fillRect(x*4,75+S(a+x/27+S(x/9)*S(a*2-x/15))*20,4,3))fillStyle='#c60'",a=9)><canvas id=R>
<body style=line-height:9px><pre id=B><script>setInterval("w='<br>';b=[,,,,,].join('P01 256b JS TUNNEX - ').substr(++t%21,65)+w;for(y=-n;n>++y;)for(b+=w,x=-n;n>++x;)b+=((399/Math.sqrt(x*x+y*y)+t)^(Math.atan2(y,x)*20.4+t))&8?'W':'&nbsp;';B.innerHTML=b",t=n=33)<>
p01<i id=d><script>setInterval('for(x=_="in solid #",E=Math,o=99,--O;o--;x+="<hr style=\'width:0;margin:auto;border-right:"+E.abs(q?p:P)+_+(9-q)*36+";border-left:"+E.abs(q?P:p)+_+(8+q)*36+"\'>")q=0>(p=E.cos(O+=22))*(P=E.sin(O));d.innerHTML=x',O=9)<>
<body id=B text=snow bgColor=0><script>O=setInterval("m='p01 256b Starfield';c=Math.cos;for(o=0;o<65;)m+='<p style=position:absolute;top:'+(50+(z=399/(73-(++o+O++&63)))*c(o*.9))+'%;left:'+(50+z*c(o))+(z>>4?'%>\u00b7':'%;color:#456>.');B.innerHTML=m",9)<>
<pre id=B><script>setInterval("for(d='p01\u2021*\xd7:,~.    ',C=Math.cos(n-=88),S=Math.sin(n),Y=m=1+C,z=2048;z;Y-=m/16)for(d+='<br>',X=m;--z&63;X-=m/32,d+=d.charAt(k))for(r=i=k=0;++k+r*r+i*i<13;i=t)t=2*r*i-X*C+Y*S,r=r*r-i*i-X*S-Y*C+C-1;B.innerHTML=d",n=9)<>*/for(a=x.innerHTML.replace(/<>/g,"<\/script>").split("\n"),i=1;i<22;i++)b.innerHTML+="<button onclick='frames[0].location.replace(\"data:text/html,\"+escape(a["+i+"]))'>"+i</script><iframe width=1100 height=600>